.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MODULO\-UPDATE" "1" "July 2017" "Modulo" "Modulo manual"
.
.SH "NAME"
\fBmodulo\-update\fR \- Update the project based on the current set of dependencies\.
.
.SH "SYNOPSIS"
\fBmodulo update\fR [\-\-all]
.
.br
\fBmodulo update\fR \fIdependencyname\fR
.
.br
.
.SH "DESCRIPTION"
This command updates any previously specified dependencies\. Updates can consist of the following:
.
.IP "\(bu" 4
Cloning any dependencies that don\'t exist in the filesystem yet\.
.
.IP "\(bu" 4
Performing a fetch on dependencies to get any new tags/branches/commits
.
.IP "\(bu" 4
Verifying that it\'s safe to check out the specified tag/branch/commit\.
.
.IP "\(bu" 4
Checking out the specified tag/branch/commit for each dependency\.
.
.IP "" 0
.
.SH "OPTIONS"
.
.TP
\fB\-a, \-\-all\fR
This will iterate through all dependencies and perform an update\.
.
.TP
\fIdependencyname\fR
Instructs Modulo to just perform an update on the specified dependency\. See \fBmap\fR for a list of dependencies\.
.
.TP
`\-\-nonzero
Returns a non\-zero result if modulo actually cloned dependencies\. This is useful for CI build systems\.
.
.TP
\fB\-\-host <host name>\fR
Checks for ability to connect to host name before continuing\. This allows for developers to work off\-line without being interrupted\.
.
.TP
\fB\-\-meh\fR
Update will perform a no\-op if modulo isn\'t being used on this project\. Useful for build system integration\.
.
.TP
\fB\-v, \-\-verbose\fR
Prints verbose output\. Use this to see what underlying SCM commands are being used and any other important information\.
.
.TP
\fB\-h, \-\-help\fR
Prints the help for this command\.
.
.SH "SEE ALSO"
modulo\-layout(1), modulo\-map(1)
.
.SH "REPORTING BUGS"
Report bugs to the Github Project located at https://github\.com/modulo\-dm/modulo/\. You\'ll be able to see the status and track any issues you create\.
.
.SH "AUTHORS"
Brandon Sneed \fIbrandon@redf\.net\fR
.
.br
Peat Bakke \fIpeat@peat\.org\fR
.
.br

